<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Task Insert</title>
</head>
<body>

    <form action="http://localhost/dev/developers-team/web/taskinsertinsert" method="post">

        <fieldset> <legend>Task Data</legend>

            <p>Name: <input type="text" name="titulo"> </p>
            <p>Assignee: <input type="text" name="assignee" id=""></p>
            <p>Start Date: <input type="date" name="startDate" id=""></p>
            <p>End Date: <input type="date" name="endDate" id=""></p>
            <p>Status: <input type="text" name="status" id=""></p>
            
        </fieldset>

        <input type="submit" value="Send">
    </form>
    
</body>
</html>